// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Hoehoe3.Core.Tests1")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Hoehoe3.Core.Tests1")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("ffc70d97-4351-4a4c-8a73-4b9613b4d36c")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]